[accessibility]
ui_scale = 1.0000000074505806

[bar.default]
center = [ "spacer_1", "clock" ]
end = [ "tray", "group:g4", "group:g2", "group:g3" ]
margin_ends = 0
radius = 0
scale = 1.0000000074505806
start = [ "workspaces", "group:g1" ]

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    border = ""
    enabled = true
    fill = "on_secondary"
    id = "g1"
    members = [ "cpu", "ram", "network_rx" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g2"
    members = [ "notifications", "network", "bluetooth", "volume" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g3"
    members = [ "settings", "switch_users", "session" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g4"
    members = [ "notes", "recorder", "dns-switcher" ]
    opacity = 1.0
    padding = 6.0

[location]
auto_locate = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 683.0
    cy = 586.0
    output = "eDP-1"
    placement_height = 768.0
    placement_width = 1366.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[plugins]
enabled = [ "noctalia/screen_recorder", "noctalia/notes", "nightwatch75/dns-switcher" ]

    [plugins."noctalia/screen_recorder"]
    audio_source = "default_output"
    directory = "~/Videos/Recordings"
    frame_rate = 60
    hide_inactive = true
    video_source = "focused"

[shell]
corner_radius_scale = 0.0
font_family = "Noto Sans"
show_shortcuts = false
    [shell.animation]
    enabled = false
    speed = 0.5000000074505806

    [shell.panel]
    session_placement = "floating"
    session_position = "center"

    [[shell.session.actions]]
    action = "lock"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "1"
    variant = "default"

    [[shell.session.actions]]
    action = "logout"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "2"
    variant = "default"

    [[shell.session.actions]]
    action = "command"
    command = "exec sh -c 'noctalia msg session lock; sleep 0.2; gdbus call --system --dest org.freedesktop.DisplayManager --object-path /org/freedesktop/DisplayManager/Seat0 --method org.freedesktop.DisplayManager.Seat.SwitchToGreeter'"
    countdown_seconds = 0.0
    enabled = true
    glyph = "users"
    label = "Switch User"
    variant = "default"

    [[shell.session.actions]]
    action = "lock_and_suspend"
    countdown_seconds = 0.0
    enabled = false
    shortcut = "3"
    variant = "default"

    [[shell.session.actions]]
    action = "reboot"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "4"
    variant = "default"

    [[shell.session.actions]]
    action = "shutdown"
    countdown_seconds = 0.0
    enabled = true
    shortcut = "5"
    variant = "destructive"

[theme]
builtin = "Tokyo-Night"
community_palette = "Oxocarbon"
mode = "dark"
source = "builtin"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "alacritty", "btop", "gtk3", "gtk4", "ghostty", "hyprland", "kcolorscheme", "kitty", "qt" ]

[wallpaper]
directory = "/home/firomsa/wallpaper"
fill_mode = "stretch"

    [wallpaper.default]
    path = "/home/firomsa/wallpaper/1-scenery-pink-lakeside-sunset-lake-landscape-scenic-panorama-7680x3215-144.png"

    [wallpaper.last]
    path = "/home/firomsa/wallpaper/1-scenery-pink-lakeside-sunset-lake-landscape-scenic-panorama-7680x3215-144.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/firomsa/wallpaper/1-scenery-pink-lakeside-sunset-lake-landscape-scenic-panorama-7680x3215-144.png"

[widget.clock]
format = "{:%H:%M, %B %d,%Y}"

[widget.dns-switcher]
type = "nightwatch75/dns-switcher:dns-switcher"

[widget.notes]
type = "noctalia/notes:notes"

[widget.recorder]
type = "noctalia/screen_recorder:recorder"


[widget.workspaces]
show_labels = false
